<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rrit_maps2_events"
 *
 * Auto generated by Extension Builder 2020-03-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RRIT Events for Maps2',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Ayke Halder, Ayke Halder',
    'author_email' => 'mail@ayke-halder.de, mail@ayke-halder.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
